name: Limpiar Repositorio

on:
  push:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Git
      uses: actions/checkout@v2
    - name: Delete Releases
      uses: sgpublic/delete-release-action@v1.2
