name: Kick to Release

on:
  workflow_dispatch:
    inputs:
      ffmpeg_url:
        description: "URL del archivo HLS para descargar"
        required: true
      file_name:
        description: "Nombre del archivo de salida"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          sudo mkdir -p /mnt/workspace
          sudo chown $USER:$USER /mnt/workspace

      - name: Download file
        working-directory: /mnt/workspace
        run: |
          ffmpeg -i "${{ github.event.inputs.ffmpeg_url }}" -c copy "${{ github.event.inputs.file_name }}"

      - name: Check file size
        working-directory: /mnt/workspace
        run: |
          file_size=$(stat -c%s "${{ github.event.inputs.file_name }}")
          echo file_size=$file_size >> $GITHUB_ENV

      - name: Split large file
        if: ${{ env.file_size >= 2147483648 }}
        working-directory: /mnt/workspace
        run: |
          split -b 1G "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.file_name }}_part_"
          rm "${{ github.event.inputs.file_name }}"

      - name: GH Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: /mnt/workspace/*
          name: ${{ github.event.inputs.file_name }}
          tag_name: ${{ github.event.inputs.file_name }}
