name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node main.mjs -m SM-A236M -r ARO -i 358263681238947

      - name: Split large file
        run: |
          # Verifica si el archivo es mayor a 2 GB y lo divide en partes
          if [ -f "SM-A236M_ARO/AP*" ] && [ $(stat -c %s SM-A236M_ARO/AP*) -gt 2147483648 ]; then
            split -b 1900M SM-A236M_ARO/AP* "SM-A236M_ARO/AP_part_"
          fi

      - name: GH Release
        if: ${{ matrix.node-version == '22.x' }}
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            SM-A236M_ARO/AP_part_*
            SM-A236M_ARO/BL*
            SM-A236M_ARO/CP*
            SM-A236M_ARO/CSC_OWO*
            SM-A236M_ARO/HOME_CSC_OWO*
          tag_name: ${{ github.run_id }}
