name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Model"
        required: true
        default: "SM-A236M"
      region:
        description: "Region"
        required: true
        default: "ARO"
      imei:
        description: "IMEI/Serial Number"
        required: true
        default: "R5CW312KLVM"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: ["ARO", "ZTO", "CHO", "TBS", "TGU", "SEM", "TPA", "UPO", "PET", "PCT", "ANC", "VNO"]
        node-version: ["22.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run script
        run: |
          node main.mjs -m ${{ inputs.model }} -r ${{ matrix.region }} -i ${{ inputs.imei }}

      - name: Split large files
        run: |
          mkdir -p ${{ inputs.model }}_${{ matrix.region }}/split
          split -b 1024m ${{ inputs.model }}_${{ matrix.region }}/AP* ${{ inputs.model }}_${{ matrix.region }}/split/AP_part_

      - name: Get latest firmware version
        run: |
          LATEST_VERSION=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ inputs.model }}/version.xml | grep -oP '(?<=<latest o="\d{02}">)[^/]+')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${{ inputs.model }}_${{ matrix.region }}/split/AP_part_*
            ${{ inputs.model }}_${{ matrix.region }}/BL*
            ${{ inputs.model }}_${{ matrix.region }}/CP*
            ${{ inputs.model }}_${{ matrix.region }}/CSC_OWO*
            ${{ inputs.model }}_${{ matrix.region }}/HOME_CSC_OWO*
          name: ${{ env.LATEST_VERSION }}
          tag_name: ${{ inputs.model }}_${{ matrix.region }}
