name: Download and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      model: SM-A236M
      region: ARO
      imei: R5CW312KLVM

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: "LunarStorm97/samfirm"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run samfirm
        run: node index.mjs -m "${{ env.model }}" -r "${{ env.region }}" -i "${{ env.imei }}"

      - name: Check file path
        run: |
          file_path=$(ls ${{ env.model }}_${{ env.region }}/AP*)
          echo "file_path=$file_path" >> $GITHUB_ENV

      - name: Check file size
        run: |
          file_size=$(stat -c%s "${{ env.file_path }}")
          echo "file_size=$file_size" >> $GITHUB_ENV

      - name: Split large file
        if: ${{ env.file_size >= 2147483648 }}
        run: |
          split -b 1G "${{ env.file_path }}" "${{ env.file_path }}_part_"
          rm "${{ env.file_path }}"

      - name: Get latest firmware version
        run: |
          latest_version=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/"${{ env.region }}/${{ env.model }}"/version.xml | grep -oP '<latest[^>]*>\K[^<]+')
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Check if tag exists
        run: |
          if git ls-remote --tags https://github.com/${{ github.repository }}.git "${{ env.latest_version }}" | grep -q "${{ env.latest_version }}"; then
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: GH Release
        if: ${{ env.tag_exists == false }}
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ env.model }}_${{ env.region }}/*
          name: ${{ env.latest_version }}
          tag_name: ${{ env.latest_version }}
