name: Node.js CI

on:
  workflow_dispatch:

env:
  model: "SM-A236M"
  imei: "R5CW312KLVM"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["22.x"]
        region: ["ARO", "CGU", "CHE", "CHL", "CHO", "CHT", "CHX", "CTI", "GLO", "GTO", "PGU", "PSN", "TPA", "UFN", "ZTA", "ZTM", "ZTO", "ZVV"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run script
        run: |
          node main.mjs -m $model -r ${{ matrix.region }} -i $imei

      - name: Split large files
        run: |
          for file in ${model}_${{ matrix.region }}/AP*; do
            split -b 1024m "$file" "${file}_part_"
            rm "$file"
          done

      - name: Get latest firmware version
        run: |
          LATEST_VERSION=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${model}/version.xml | grep -oP '(?<=<latest o="\d{02}">)[^/]+')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${model}_${{ matrix.region }}/*
          name: ${{ env.LATEST_VERSION }}
          tag_name: ${model}_${{ matrix.region }}
