name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        imei: ["R5CW312KLVM"]
        model: ["SM-A236M"]
        node-version: ["22.x"]
        region: ["ARO", "CGU", "CHE", "CHL", "CHO", "CHT", "CHX", "CTI", "GLO", "GTO", "PGU", "PSN", "TPA", "UFN", "ZTA", "ZTM", "ZTO", "ZVV"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run script
        run: |
          node main.mjs -m ${{ matrix.model }} -r ${{ matrix.region }} -i ${{ matrix.imei }}

      - name: Split large files
        run: |
          mkdir -p ${{ matrix.model }}_${{ matrix.region }}/split
          split -b 1024m ${{ matrix.model }}_${{ matrix.region }}/AP* ${{ matrix.model }}_${{ matrix.region }}/split/AP_part_

      - name: Get latest firmware version
        run: |
          LATEST_VERSION=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ matrix.model }}/version.xml | grep -oP '(?<=<latest o="\d{02}">)[^/]+')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${{ matrix.model }}_${{ matrix.region }}/split/AP_part_*
            ${{ matrix.model }}_${{ matrix.region }}/BL*
            ${{ matrix.model }}_${{ matrix.region }}/CP*
            ${{ matrix.model }}_${{ matrix.region }}/CSC_OWO*
            ${{ matrix.model }}_${{ matrix.region }}/HOME_CSC_OWO*
          name: ${{ env.LATEST_VERSION }}
          tag_name: ${{ matrix.model }}_${{ matrix.region }}
