# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node index.mjs -m SM-A236M -r ARO -i 358263681238947
      - name: Upload SM files as artifact
        if: matrix.node-version == '22.x'
        uses: actions/upload-artifact@v4.5.0
        with:
          name: SM-files
          path: |
            SM*/BL*
            SM*/CP*
            SM*/CSC*
            SM*/HOME*

      - name: Set up Git LFS
        if: matrix.node-version == '22.x'
        run: |
          rm -rf SM*/AP*
          git lfs install
          git lfs track "*.tar.md5"
          git add .gitattributes
          git commit -m "Track large files using Git LFS"

      - name: Commit and Push SM Files
        if: matrix.node-version == '22.x'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add SM*
          git commit -m "Add SM files"
          git push
