name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Model"
        required: true
        default: "SM-A236M"
      region:
        description: "Region"
        required: true
        default: "ARO"
      imei:
        description: "IMEI/Serial Number"
        required: true
        default: "R5CW312KLVM"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: 
          - ARO  # Argentina (Libre)
          - CTI  # Argentina (Claro)
          - PSN  # Argentina (Personal)
          - UFN  # Argentina (Movistar)
          - BVO  # Bolivia (Libre)
          - BVT  # Bolivia (Tigo)
          - ZTO  # Brasil (Libre)
          - ZTA  # Brasil (Claro)
          - ZTR  # Brasil (Oi)
          - ZTM  # Brasil (TIM)
          - ZVV  # Brasil (Vivo)
          - CHO  # Chile (Libre)
          - CHL  # Chile (Claro)
          - CHE  # Chile (Entel)
          - CHT  # Chile (Telefónica)
          - COO  # Colombia (Libre)
          - COM  # Colombia (Comcel)
          - COB  # Colombia (Movistar)
          - ICE  # Costa Rica (ICE/Kölbi)
          - CRC  # Costa Rica (Claro)
          - CRM  # Costa Rica (Movistar)
          - ECO  # Ecuador (Libre)
          - ALE  # Ecuador (Alegro)
          - TBS  # El Salvador (Libre)
          - TGU  # Guatemala (Movistar)
          - PGU  # Guatemala (Claro)
          - CGU  # Guatemala (Tigo)
          - CWW  # Jamaica (Cable & Wireless)
          - TMM  # México (Movistar)
          - TCE  # México (Telcel)
          - IUS  # México (Iusacell)
          - UNE  # México (Unefon)
          - SEM  # México (Libre)
          - TPA  # Panamá (Libre)
          - CPA  # Panamá (Claro)
          - PBS  # Panamá (PBS)
          - CTP  # Paraguay (Claro)
          - UPO  # Paraguay (Libre)
          - PET  # Perú (Libre)
          - SAM  # Perú (SAM)
          - PNT  # Perú (Nextel)
          - WP   # Perú (Movistar)
          - PCT  # Puerto Rico (Libre)
          - CDR  # República Dominicana (Claro)
          - DOR  # República Dominicana (Orange)
          - ANC  # Uruguay (Libre)
          - CTU  # Uruguay (Claro)
          - UFU  # Uruguay (Movistar)
          - VMT  # Venezuela (Movistar)
          - VNO  # Venezuela (Libre)

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run script
        run: |
        continue-on-error: true
          node main.mjs -m ${{ inputs.model }} -r ${{ matrix.region }} -i ${{ inputs.imei }}

      - name: Split large files
        run: |
        continue-on-error: true
          mkdir -p ${{ inputs.model }}_${{ matrix.region }}/split
          split -b 1024m ${{ inputs.model }}_${{ matrix.region }}/AP* ${{ inputs.model }}_${{ matrix.region }}/split/AP_part_

      - name: Get latest firmware version
        run: |
        continue-on-error: true
          LATEST_VERSION=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ inputs.model }}/version.xml | grep -oP '(?<=<latest o="\d{02}">)[^/]+')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${{ inputs.model }}_${{ matrix.region }}/split/AP_part_*
            ${{ inputs.model }}_${{ matrix.region }}/BL*
            ${{ inputs.model }}_${{ matrix.region }}/CP*
            ${{ inputs.model }}_${{ matrix.region }}/CSC_OWO*
            ${{ inputs.model }}_${{ matrix.region }}/HOME_CSC_OWO*
          name: ${{ env.LATEST_VERSION }}
          tag_name: ${{ inputs.model }}_${{ matrix.region }}
