name: Download and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  MODEL: SM-A236M
  REGION: ARO
  IMEI: R5CW312KLVM

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: "LunarStorm97/samfirm"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run samfirm
        run: node index.mjs -m "$MODEL" -r "${{ env.REGION }}" -i "${{ env.IMEI }}"

      - name: Check file path
        run: |
          FILE_PATH=$(ls "${{ env.MODEL }}_${{ env.REGION }}"/AP*)
          echo "FILE_PATH=$FILE_PATH" >> "$GITHUB_ENV"

      - name: Check file size
        run: |
          FILE_SIZE=$(stat -c%s "${{ env.FILE_PATH }}")
          echo "FILE_SIZE=$FILE_SIZE" >> "$GITHUB_ENV"

      - name: Split large file
        if: ${{ env.FILE_SIZE >= 2147483648 }}
        run: |
          split -b 1G "${{ env.FILE_PATH }}" "${{ env.FILE_PATH }}_part_"
          rm "${{ env.FILE_PATH }}"

      - name: Get latest firmware version
        run: |
          LATEST_VERSION=$(curl -s "http://fota-cloud-dn.ospserver.net/firmware/${{ env.REGION }}/${{ env.MODEL }}/version.xml" | grep -oP "<latest[^>]*>\K[^<]+")
          echo "LATEST_VERSION=$LATEST_VERSION" >> "$GITHUB_ENV"

      - name: Check if tag exists
        run: |
          if git ls-remote --tags "https://github.com/${{ github.repository }}.git" "${{ env.LATEST_VERSION }}" | grep -q "${{ env.LATEST_VERSION }}"; then
            echo "TAG_EXISTS=true" >> "$GITHUB_ENV"
          else
            echo "TAG_EXISTS=false" >> "$GITHUB_ENV"
          fi

      - name: GH Release
        if: ${{ env.TAG_EXISTS == 'false' }}
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ env.MODEL }}_${{ env.REGION }}/*
          name: ${{ env.LATEST_VERSION }}
          tag_name: ${{ env.LATEST_VERSION }}
