name: Node.js CI

on:
  push:
  workflow_dispatch:
    inputs:
      model:
        description: "Model"
        required: true
        default: "SM-A236M"
      region:
        description: "Region"
        required: true
        default: "ARO"
      imei:
        description: "IMEI/Serial Number"
        required: false
        default: "358263681238947"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node main.mjs -m ${{ inputs.model }} -r ${{ inputs.region }} -i ${{ inputs.imei }}

      - name: Split large files
        run: |
          mkdir -p ${{ inputs.model }}_${{ inputs.region }}/split
          split -b 2000000000 ${{ inputs.model }}_${{ inputs.region }}/AP* ${{ inputs.model }}_${{ inputs.region }}/split/AP_part_

      - name: GH Release
        if: ${{ matrix.node-version == '22.x' }}
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${{ inputs.model }}_${{ inputs.region }}/split/AP_part_*
            ${{ inputs.model }}_${{ inputs.region }}/BL*
            ${{ inputs.model }}_${{ inputs.region }}/CP*
            ${{ inputs.model }}_${{ inputs.region }}/CSC_OWO*
            ${{ inputs.model }}_${{ inputs.region }}/HOME_CSC_OWO*
          tag_name: ${{ github.run_id }}
