name: Download and Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: "LunarStorm97/samfirm"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.mjs -m SM-A236M -r ARO -i R5CW312KLVM

      - name: Download file
        run: |
          file_name=$(ls SM-A236M_ARO/*)
          echo "file_name=$file_name" >> $GITHUB_ENV

      - name: Check file size
        run: |
          file_size=$(stat -c%s SM-A236M_ARO/"${{ env.file_name }}")
          echo "file_size=$file_size" >> $GITHUB_ENV

      - name: Split large file
        if: ${{ env.file_size >= 2147483648 }}
        run: |
          split -b 1G SM-A236M_ARO/"${{ env.file_name }}" SM-A236M_ARO/"${{ env.file_name }}_part_"
          rm SM-A236M_ARO/"${{ env.file_name }}"

      - name: Get latest firmware version
        run: |
          latest_version=$(curl -s http://fota-cloud-dn.ospserver.net/firmware/ARO/SM-A236M/version.xml | grep -oP '<latest[^>]*>\K[^<]+')
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Check if tag exists
        run: |
          if git ls-remote --tags https://github.com/${{ github.repository }}.git "$latest_version" | grep -q "$latest_version"; then
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: GH Release
        if: env.tag_exists == 'false'
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: SM-A236M_ARO/*
          name: ${{ env.file_name }}
          tag_name: ${{ env.file_name }}
